[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "node dist/main.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/docs"
healthcheckTimeout = 120
