-- Run once when DB_SYNCHRONIZE=false (party / bulk orders feature)
CREATE TABLE IF NOT EXISTS party_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "partyName" character varying NOT NULL,
  "totalAmount" double precision NOT NULL,
  "discountPercent" double precision NOT NULL DEFAULT 0,
  "amountAfterDiscount" double precision NOT NULL,
  "totalEarnings" double precision NOT NULL,
  "paymentMethod" orders_paymentmethod_enum NOT NULL DEFAULT 'CASH'::orders_paymentmethod_enum,
  "userId" BIGINT REFERENCES users(id) ON DELETE SET NULL,
  note text,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_party_orders_created_at ON party_orders ("createdAt" DESC);
CREATE INDEX IF NOT EXISTS idx_party_orders_user_id ON party_orders ("userId");
