-- Run once when DB_SYNCHRONIZE=false
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description character varying NOT NULL,
  amount double precision NOT NULL,
  spoc character varying NOT NULL,
  "expenseDate" date NOT NULL DEFAULT CURRENT_DATE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE expenses
  ADD COLUMN IF NOT EXISTS "expenseDate" date NOT NULL DEFAULT CURRENT_DATE;

UPDATE expenses
SET "expenseDate" = "createdAt"::date
WHERE "expenseDate" IS NULL;

CREATE INDEX IF NOT EXISTS idx_expenses_expense_date ON expenses ("expenseDate" DESC);

-- Seed spreadsheet data (skip if same description + amount already exists)
INSERT INTO expenses (description, amount, spoc, "expenseDate")
SELECT v.description, v.amount, v.spoc, v.expense_date::date
FROM (
  VALUES
    ('Dustbin Covers', 215, 'Sai', '2026-06-01'),
    ('Dmart (Tissues,Book,Pens)', 354, 'Sai', '2026-06-01'),
    ('Garbage Covers via Amazon', 583, 'Sai', '2026-06-01'),
    ('Ice Cubes', 245, 'Sai', '2026-06-01'),
    ('Parcel Covers', 180, 'Sai', '2026-06-01'),
    ('Employee Salary for 2 Days', 800, 'Sai', '2026-06-01'),
    ('1,2,5,10 Rupee Coins', 1000, 'Sai', '2026-06-01'),
    ('Dmart (Tissues,Lyzol,Pens)', 902, 'Sai', '2026-06-01'),
    ('Plastic Mat', 260, 'Sai', '2026-06-01'),
    ('Water Bottles', 200, 'Sai', '2026-06-01'),
    ('Nostic Sai March Salary', 3200, 'Sai', '2026-03-01'),
    ('Nostic Sai April Advance Salary', 10000, 'Sai', '2026-04-01')
) AS v(description, amount, spoc, expense_date)
WHERE NOT EXISTS (
  SELECT 1 FROM expenses e
  WHERE e.description = v.description AND e.amount = v.amount
);
