-- Migrate UUID primary keys to BIGINT GENERATED BY DEFAULT AS IDENTITY (PostgreSQL).
-- Preserves existing row data and foreign-key relationships.
-- Safe to re-run: exits early if users.id is already integer/bigint.
--
-- Run from backend folder:
--   npm run db:migrate-ids
--
-- After migration: log in again (old JWTs reference UUID subs).

BEGIN;

DO $$
DECLARE
  users_id_type text;
BEGIN
  SELECT data_type INTO users_id_type
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'users'
    AND column_name = 'id';

  IF users_id_type IS NULL THEN
    RAISE NOTICE 'users table not found — nothing to migrate';
    RETURN;
  END IF;

  IF users_id_type IN ('integer', 'bigint', 'smallint') THEN
    RAISE NOTICE 'users.id is already numeric (%), skipping migration', users_id_type;
    RETURN;
  END IF;

  RAISE NOTICE 'Migrating UUID keys to identity columns...';

  -- ── Users ──────────────────────────────────────────────────────────────
  CREATE TABLE users_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_uuid UUID NOT NULL UNIQUE,
    name character varying(100) NOT NULL,
    email character varying(100) NOT NULL UNIQUE,
    phone character varying(15),
    password character varying NOT NULL,
    role users_role_enum NOT NULL DEFAULT 'staff'::users_role_enum,
    "branchCode" character varying(10),
    "isActive" boolean NOT NULL DEFAULT true,
    "failedLoginAttempts" integer NOT NULL DEFAULT 0,
    "lockedUntil" TIMESTAMP WITH TIME ZONE,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  );

  INSERT INTO users_new (
    legacy_uuid, name, email, phone, password, role,
    "branchCode", "isActive", "failedLoginAttempts", "lockedUntil",
    "createdAt", "updatedAt"
  )
  SELECT
    id, name, email, phone, password, role,
    "branchCode", "isActive", "failedLoginAttempts", "lockedUntil",
    "createdAt", "updatedAt"
  FROM users;

  -- ── Flavors ────────────────────────────────────────────────────────────
  CREATE TABLE flavors_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_uuid UUID NOT NULL UNIQUE,
    name character varying UNIQUE,
    category character varying,
    description text,
    price double precision NOT NULL DEFAULT 0,
    stock double precision NOT NULL DEFAULT 0,
    "minStock" double precision NOT NULL DEFAULT 10,
    image character varying,
    "isActive" boolean NOT NULL DEFAULT true,
    "isSeasonal" boolean NOT NULL DEFAULT false,
    popularity integer NOT NULL DEFAULT 0,
    "reservedQty" double precision NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  );

  INSERT INTO flavors_new (
    legacy_uuid, name, category, description, price, stock, "minStock",
    image, "isActive", "isSeasonal", popularity, "reservedQty",
    "createdAt", "updatedAt"
  )
  SELECT
    id, name, category, description, price, stock, "minStock",
    image, "isActive", "isSeasonal", popularity, "reservedQty",
    "createdAt", "updatedAt"
  FROM flavors;

  -- ── Orders ─────────────────────────────────────────────────────────────
  CREATE TABLE orders_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_uuid UUID NOT NULL UNIQUE,
    status orders_status_enum NOT NULL DEFAULT 'PENDING'::orders_status_enum,
    "paymentMethod" orders_paymentmethod_enum NOT NULL DEFAULT 'CASH'::orders_paymentmethod_enum,
    "userId" BIGINT REFERENCES users_new(id) ON DELETE SET NULL,
    total double precision NOT NULL DEFAULT 0,
    note text,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  );

  INSERT INTO orders_new (
    legacy_uuid, status, "paymentMethod", "userId", total, note,
    "createdAt", "updatedAt"
  )
  SELECT
    o.id, o.status, o."paymentMethod", u.id, o.total, o.note,
    o."createdAt", o."updatedAt"
  FROM orders o
  LEFT JOIN users_new u ON u.legacy_uuid = o."userId";

  -- ── Refresh tokens ─────────────────────────────────────────────────────
  CREATE TABLE refresh_tokens_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_uuid UUID NOT NULL UNIQUE,
    "userId" BIGINT NOT NULL REFERENCES users_new(id) ON DELETE CASCADE,
    "tokenHash" character varying NOT NULL UNIQUE,
    "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "revokedAt" TIMESTAMP WITH TIME ZONE,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  );

  INSERT INTO refresh_tokens_new (
    legacy_uuid, "userId", "tokenHash", "expiresAt", "revokedAt", "createdAt"
  )
  SELECT
    rt.id, u.id, rt."tokenHash", rt."expiresAt", rt."revokedAt", rt."createdAt"
  FROM refresh_tokens rt
  JOIN users_new u ON u.legacy_uuid = rt."userId";

  -- ── Flavor monthly ─────────────────────────────────────────────────────
  CREATE TABLE flavor_monthly_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_uuid UUID NOT NULL UNIQUE,
    "flavorId" BIGINT NOT NULL REFERENCES flavors_new(id) ON DELETE CASCADE,
    month integer NOT NULL,
    year integer NOT NULL,
    "carryForwarded" double precision NOT NULL DEFAULT 0,
    quantity double precision NOT NULL DEFAULT 0,
    rate double precision NOT NULL DEFAULT 0,
    cost double precision NOT NULL DEFAULT 0,
    category character varying,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  );

  INSERT INTO flavor_monthly_new (
    legacy_uuid, "flavorId", month, year, "carryForwarded", quantity,
    rate, cost, category, "createdAt"
  )
  SELECT
    fm.id, f.id, fm.month, fm.year, fm."carryForwarded", fm.quantity,
    fm.rate, fm.cost, fm.category, fm."createdAt"
  FROM flavor_monthly fm
  JOIN flavors_new f ON f.legacy_uuid = fm."flavorId";

  -- ── Order items ────────────────────────────────────────────────────────
  CREATE TABLE order_items_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_uuid UUID NOT NULL UNIQUE,
    "orderId" BIGINT NOT NULL REFERENCES orders_new(id) ON DELETE CASCADE,
    "flavorId" BIGINT NOT NULL REFERENCES flavors_new(id),
    quantity double precision NOT NULL DEFAULT 0,
    "unitPrice" double precision NOT NULL DEFAULT 0,
    "totalPrice" double precision NOT NULL DEFAULT 0
  );

  INSERT INTO order_items_new (
    legacy_uuid, "orderId", "flavorId", quantity, "unitPrice", "totalPrice"
  )
  SELECT
    oi.id, o.id, f.id, oi.quantity, oi."unitPrice", oi."totalPrice"
  FROM order_items oi
  JOIN orders_new o ON o.legacy_uuid = oi."orderId"
  JOIN flavors_new f ON f.legacy_uuid = oi."flavorId";

  -- ── Inventory transactions ─────────────────────────────────────────────
  CREATE TABLE inventory_transactions_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_uuid UUID NOT NULL UNIQUE,
    "flavorId" BIGINT NOT NULL REFERENCES flavors_new(id),
    change double precision NOT NULL,
    type inventory_transactions_type_enum NOT NULL,
    reason text,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  );

  INSERT INTO inventory_transactions_new (
    legacy_uuid, "flavorId", change, type, reason, "createdAt"
  )
  SELECT
    it.id, f.id, it.change, it.type, it.reason, it."createdAt"
  FROM inventory_transactions it
  JOIN flavors_new f ON f.legacy_uuid = it."flavorId";

  -- ── Payments ───────────────────────────────────────────────────────────
  CREATE TABLE payments_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_uuid UUID NOT NULL UNIQUE,
    "orderId" BIGINT NOT NULL REFERENCES orders_new(id) ON DELETE CASCADE,
    "merchantTransactionId" character varying NOT NULL UNIQUE,
    "phonepeReferenceId" character varying,
    "amountPaise" double precision NOT NULL,
    status payments_status_enum NOT NULL DEFAULT 'PENDING'::payments_status_enum,
    "qrString" text,
    "expiresAt" TIMESTAMP WITH TIME ZONE,
    "phonepeCode" character varying,
    "phonepeMessage" text,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  );

  INSERT INTO payments_new (
    legacy_uuid, "orderId", "merchantTransactionId", "phonepeReferenceId",
    "amountPaise", status, "qrString", "expiresAt", "phonepeCode",
    "phonepeMessage", "createdAt", "updatedAt"
  )
  SELECT
    p.id, o.id, p."merchantTransactionId", p."phonepeReferenceId",
    p."amountPaise", p.status, p."qrString", p."expiresAt", p."phonepeCode",
    p."phonepeMessage", p."createdAt", p."updatedAt"
  FROM payments p
  JOIN orders_new o ON o.legacy_uuid = p."orderId";

  -- ── Swap tables ────────────────────────────────────────────────────────
  DROP TABLE IF EXISTS payments CASCADE;
  DROP TABLE IF EXISTS order_items CASCADE;
  DROP TABLE IF EXISTS inventory_transactions CASCADE;
  DROP TABLE IF EXISTS flavor_monthly CASCADE;
  DROP TABLE IF EXISTS refresh_tokens CASCADE;
  DROP TABLE IF EXISTS orders CASCADE;
  DROP TABLE IF EXISTS flavors CASCADE;
  DROP TABLE IF EXISTS users CASCADE;

  ALTER TABLE users_new RENAME TO users;
  ALTER TABLE flavors_new RENAME TO flavors;
  ALTER TABLE orders_new RENAME TO orders;
  ALTER TABLE refresh_tokens_new RENAME TO refresh_tokens;
  ALTER TABLE flavor_monthly_new RENAME TO flavor_monthly;
  ALTER TABLE order_items_new RENAME TO order_items;
  ALTER TABLE inventory_transactions_new RENAME TO inventory_transactions;
  ALTER TABLE payments_new RENAME TO payments;

  ALTER TABLE users DROP COLUMN legacy_uuid;
  ALTER TABLE flavors DROP COLUMN legacy_uuid;
  ALTER TABLE orders DROP COLUMN legacy_uuid;
  ALTER TABLE refresh_tokens DROP COLUMN legacy_uuid;
  ALTER TABLE flavor_monthly DROP COLUMN legacy_uuid;
  ALTER TABLE order_items DROP COLUMN legacy_uuid;
  ALTER TABLE inventory_transactions DROP COLUMN legacy_uuid;
  ALTER TABLE payments DROP COLUMN legacy_uuid;

  -- Reset identity sequences to max(id)
  PERFORM setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1), true);
  PERFORM setval(pg_get_serial_sequence('flavors', 'id'), COALESCE((SELECT MAX(id) FROM flavors), 1), true);
  PERFORM setval(pg_get_serial_sequence('orders', 'id'), COALESCE((SELECT MAX(id) FROM orders), 1), true);
  PERFORM setval(pg_get_serial_sequence('refresh_tokens', 'id'), COALESCE((SELECT MAX(id) FROM refresh_tokens), 1), true);
  PERFORM setval(pg_get_serial_sequence('flavor_monthly', 'id'), COALESCE((SELECT MAX(id) FROM flavor_monthly), 1), true);
  PERFORM setval(pg_get_serial_sequence('order_items', 'id'), COALESCE((SELECT MAX(id) FROM order_items), 1), true);
  PERFORM setval(pg_get_serial_sequence('inventory_transactions', 'id'), COALESCE((SELECT MAX(id) FROM inventory_transactions), 1), true);
  PERFORM setval(pg_get_serial_sequence('payments', 'id'), COALESCE((SELECT MAX(id) FROM payments), 1), true);

  RAISE NOTICE 'Migration complete — all primary keys are now BIGINT identity columns';
END $$;

COMMIT;
